


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://13.232.2.228:8761/eureka}

server:
  port: 8050
spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avnadmin:AVNS_ESgA4tn3IPpnJH_9ilc@mysql-2d3775d9-aravindmunna240-b11d.d.aivencloud.com:11681/buildlive_userdb?ssl-mode=REQUIRED
    username: avnadmin
    password: 'AVNS_ESgA4tn3IPpnJH_9ilc'
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


