server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buildlive_userdb
    username: root
    password: '@77SUDHA'
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  database-platform: org.hibernate.dialect.MYSQLDialect
